_target_: tapeagents.agent.Agent
name : react_agent
max_iterations: 10
llms:
  default: ${llm}
templates: {}
nodes:
  - _target_: agentlab.agents.tapeagent.agent.ToolCallNode
    name: react
    system_prompt: |
      You are an expert AI Agent trained to assist users with complex web tasks.
      Your role is to understand the goal, perform actions until the goal is accomplished and respond in a helpful and accurate manner.
      Keep your replies concise and direct. Prioritize clarity and avoid over-elaboration.
      Do not express emotions or opinions.
    guidance: |
      Think along the following lines:
        1. Summarize the last observation and describe the visible changes in the state.
        2. Evaluate action success, explain impact on task/plan. 
        3. If there are any errors, describe them and propose alternative.
        4. List next steps to move towards the goaland propose next immediate action.
      The produce the function call that performs the proposed step. If the task is complete, produce the final step.
    steps:
      - tapeagents.core.FinalStep
    next_node: react