"""
Baseline agent for all ServiceNow papers

This module contains the GenericAgent class, which is the baseline agent for all ServiceNow papers. \
It is a simple agent that can be ran OOB on all BrowserGym environments. It is also shipped with \
a few configurations that can be used to run it on different environments.
"""

from .agent_configs import (
    AGENT_3_5,
    AGENT_8B,
    AGENT_37_SONNET,
    AGENT_CLAUDE_SONNET_35,
    AGENT_CLAUDE_SONNET_35_VISION,
    AGENT_CUSTOM,
    AGENT_LLAMA3_70B,
    AGENT_LLAMA4_17B_INSTRUCT,
    AGENT_LLAMA31_70B,
    CHAT_MODEL_ARGS_DICT,
    RANDOM_SEARCH_AGENT,
    AGENT_4o,
    AGENT_4o_MINI,
    AGENT_4o_MINI_VISION,
    AGENT_4o_VISION,
    AGENT_AZURE_4o_MINI,
    AGENT_AZURE_4o,
    AGENT_AZURE_4o_VISION,
    AGENT_AZURE_4o_MINI_VISION,
    AGENT_AZURE_41,
    AGENT_AZURE_41_MINI,
    AGENT_AZURE_41_NANO,
    AGENT_AZURE_41_VISION,
    AGENT_AZURE_41_MINI_VISION,
    AGENT_AZURE_41_NANO_VISION,
    AGENT_AZURE_5,
    AGENT_AZURE_5_MINI,
    AGENT_AZURE_5_NANO,
    AGENT_AZURE_5_VISION,
    AGENT_AZURE_5_MINI_VISION,
    AGENT_AZURE_5_NANO_VISION,
    AGENT_o1_MINI,
    AGENT_o3_MINI,
    FLAGS_GPT_4o,
    GenericAgentArgs,
    AGENT_GPT5_MINI,
)

__all__ = [
    "AGENT_3_5",
    "AGENT_4o",
    "AGENT_4o_MINI",
    "AGENT_4o_VISION",
    "AGENT_o3_MINI",
    "AGENT_o1_MINI",
    "AGENT_LLAMA4_17B_INSTRUCT",
    "AGENT_LLAMA3_70B",
    "AGENT_LLAMA31_70B",
    "AGENT_8B",
    "RANDOM_SEARCH_AGENT",
    "AGENT_CUSTOM",
    "AGENT_CLAUDE_SONNET_35",
    "AGENT_37_SONNET",
    "AGENT_4o_VISION",
    "AGENT_4o_MINI_VISION",
    "AGENT_AZURE_4o_MINI",
    "AGENT_AZURE_4o",
    "AGENT_AZURE_4o_VISION",
    "AGENT_AZURE_4o_MINI_VISION",
    "AGENT_AZURE_41",
    "AGENT_AZURE_41_MINI",
    "AGENT_AZURE_41_NANO",
    "AGENT_AZURE_41_VISION",
    "AGENT_AZURE_41_MINI_VISION",
    "AGENT_AZURE_41_NANO_VISION",
    "AGENT_AZURE_5",
    "AGENT_AZURE_5_MINI",
    "AGENT_AZURE_5_NANO",
    "AGENT_AZURE_5_VISION",
    "AGENT_AZURE_5_MINI_VISION",
    "AGENT_AZURE_5_NANO_VISION",
    "AGENT_CLAUDE_SONNET_35_VISION",
    "AGENT_GPT5_MINI",
]
