name: Update Docs with Versioning

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Run Sphinx-apidoc
      run: |
        cd docs
        sphinx-apidoc ../src -o ./source

    - name: Commit and Push to Generated Docs Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b generated-docs
        git add .
        git commit -m "Update docs for version $GITHUB_REF_NAME [skip ci]" || echo "No changes to commit"
        git push origin generated-docs --force
        git tag docs/$GITHUB_REF_NAME
        git push origin tag docs/$GITHUB_REF_NAME
